#!/usr/bin/env python3
import html
import os
import subprocess
import sys
import tempfile
from pathlib import Path

CSS = """
body { font-family: Arial, Helvetica, sans-serif; margin: 40px; color: #111; line-height: 1.45; }
h1, h2, h3, h4 { color: #111; margin-top: 1.2em; }
h1 { font-size: 28px; border-bottom: 2px solid #ddd; padding-bottom: 8px; }
h2 { font-size: 22px; border-bottom: 1px solid #eee; padding-bottom: 4px; }
h3 { font-size: 18px; }
p, li { font-size: 13px; }
code { background: #f5f5f5; padding: 2px 4px; border-radius: 4px; }
a { color: #0b57d0; text-decoration: none; }
a:hover { text-decoration: underline; }
ul { padding-left: 20px; }
hr { border: none; border-top: 1px solid #ddd; margin: 24px 0; }
.small { color: #666; font-size: 11px; }
"""


def inline_format(text: str) -> str:
    text = html.escape(text)
    text = text.replace("**", "__BOLD__")
    parts = text.split("__BOLD__")
    for i in range(1, len(parts), 2):
        parts[i] = f"<strong>{parts[i]}</strong>"
    text = "".join(parts)
    return text


def markdown_to_html(md: str) -> str:
    lines = md.splitlines()
    out = []
    in_list = False
    in_code = False
    code_buf = []

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    def close_code():
        nonlocal in_code, code_buf
        if in_code:
            out.append("<pre><code>%s</code></pre>" % html.escape("\n".join(code_buf)))
            in_code = False
            code_buf = []

    for raw in lines:
        line = raw.rstrip("\n")
        stripped = line.strip()

        if stripped.startswith("```"):
            close_list()
            if in_code:
                close_code()
            else:
                in_code = True
            continue

        if in_code:
            code_buf.append(line)
            continue

        if not stripped:
            close_list()
            out.append("")
            continue

        if stripped == "---":
            close_list()
            out.append("<hr />")
            continue

        if stripped.startswith("# "):
            close_list()
            out.append(f"<h1>{inline_format(stripped[2:])}</h1>")
            continue
        if stripped.startswith("## "):
            close_list()
            out.append(f"<h2>{inline_format(stripped[3:])}</h2>")
            continue
        if stripped.startswith("### "):
            close_list()
            out.append(f"<h3>{inline_format(stripped[4:])}</h3>")
            continue
        if stripped.startswith("#### "):
            close_list()
            out.append(f"<h4>{inline_format(stripped[5:])}</h4>")
            continue

        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{inline_format(stripped[2:])}</li>")
            continue

        close_list()
        out.append(f"<p>{inline_format(stripped)}</p>")

    close_list()
    close_code()
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: render_report_pdf.py <input.md> <output.pdf>", file=sys.stderr)
        return 2

    input_path = Path(sys.argv[1]).resolve()
    output_path = Path(sys.argv[2]).resolve()

    if not input_path.exists():
        print(f"Input not found: {input_path}", file=sys.stderr)
        return 1

    chrome = shutil_which("google-chrome-stable") or shutil_which("google-chrome")
    if not chrome:
        print("Chrome not found. Install google-chrome-stable first.", file=sys.stderr)
        return 1

    html_body = markdown_to_html(input_path.read_text(encoding="utf-8"))
    full_html = f"""<!doctype html>
<html>
<head>
<meta charset=\"utf-8\" />
<title>{html.escape(input_path.stem)}</title>
<style>{CSS}</style>
</head>
<body>
{html_body}
<p class=\"small\">Generated by render_report_pdf.py</p>
</body>
</html>
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        html_path = Path(tmpdir) / "report.html"
        html_path.write_text(full_html, encoding="utf-8")
        cmd = [
            chrome,
            "--headless=new",
            "--disable-gpu",
            "--no-sandbox",
            f"--print-to-pdf={output_path}",
            str(html_path),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            sys.stderr.write(result.stderr or result.stdout)
            return result.returncode

    print(output_path)
    return 0


def shutil_which(name: str):
    for p in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(p) / name
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


if __name__ == "__main__":
    raise SystemExit(main())
